version: "3"
services:
  freshrss:
    image: "freshrss/freshrss:arm"
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extensions:/var/www/FreshRSS/extensions
    ports:
      - "${PORT}:80"
    environment:
      TZ: '${TZ}'
      CRON_MIN: '13,43'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.hostname==${HOSTNAME}"

volumes:
  freshrss-data:
  freshrss-extensions:
