version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - "${PORT}:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      TZ: '${TZ}'
      GF_RENDERING_SERVER_URL: http://grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "${SMTP_HOST}"
      GF_SMTP_USER: "${SMTP_USER}"
      GF_SMTP_PASSWORD: "${SMTP_PASSWORD}"
      GF_SMTP_FROM_ADDRESS: "${SMTP_FROM_ADDRESS}"
      GF_SMTP_FROM_NAME: "Grafana"
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.hostname==${HOSTNAME}"
  grafana-renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    deploy:
      placement:
        constraints:
          - "node.hostname==${HOSTNAME}"

volumes:
  grafana:
