version: "3.4"

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    - HBOX_ALLOW_REGISTRATION=false
    volumes:
      - homebox-data:/data/
    ports:
      - ${PORT}:7745
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.hostname=${HOSTNAME}"

volumes:
   homebox-data:
