version: "3"
services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - lidarr_config:/config
      - ${DATA_DIR}:/data  # e.g. /data/lidarr
    ports:
      - ${PORT}:8686
    networks:
      - the_arrs
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.hostname==${HOSTNAME}"

volumes:
  lidarr_config:

networks:
  the_arrs:
    external: true