version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "${HTTP_PORT}:80/tcp"
      - "${HTTPS_PORT}:443/tcp"
    environment:
      TZ: '${TZ}'
      VIRTUAL_HOST: '${VIRTUAL_HOST}'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      WEBPASSWORD: '${PASSWORD}'
    # Volumes store your data between container upgrades
    volumes:
      - pihole-etc:/etc/pihole/
      - pihole-dnsmasq:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.hostname==${HOSTNAME}"
  pihole-exporter:
    image: pihole-exporter:latest
    ports:
      - "${PROM_EXPORTER_PORT}:9617/tcp"
    environment:
      PIHOLE_HOSTNAME: localhost
      PIHOLE_PASSWORD: '${PASSWORD}'
      PIHOLE_PORT: 80
      INTERVAL: 30s
      PORT: 9617
    # Volumes store your data between container upgrades
    volumes:
      - pihole-exporter-certs:/etc/ssl/certs
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.hostname==${HOSTNAME}"

volumes:
  pihole-etc:
  pihole-dnsmasq:
  pihole-exporter-certs:
