version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    environment:
      - TZ=${TZ}
    ports:
      - ${PORT}:9090
    volumes:
      - prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    deploy:
      placement:
        constraints:
          - "node.hostname==${HOSTNAME}"

volumes:
  prometheus:
  prometheus-data: