version: '3'
services:
  snapdrop:
    image: ghcr.io/linuxserver/snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - snapdrop:/config
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - 'node.hostname==${HOSTNAME}'

volumes:
  snapdrop:
