version: "3"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - sonarr_config:/config
      - ${DATA_DIR}:/data  # e.g. /data/sonarr
    ports:
      - ${PORT}:8989
    networks:
      - the_arrs
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.hostname==${HOSTNAME}"

volumes:
  sonarr_config:

networks:
  the_arrs:
    external: true
